### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by riberaborrell** [LuzieH/pytpt#3]
Work with this basic example: 3 states with a random transition matrix. 
-  stationary
-  time-dependent examples: finite time (at least 3 time points) and
-  periodic (at least 2 timepoints)

**Comment by eborrell** [comment]
- committors should be between 0 and 1
- backward transition matrix should be a stochastic matrix
- stationary distribution should be the stationary distribution of P and P^-
- check nan values.
- normalized reactive density should be normalized.
- check shape of returned ndarrays.
- check that the data is created.

**Comment by eborrell** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by LuzieH** [comment]
https://docs.pytest.org/en/latest/goodpractices.html#use-tox

**Comment by LuzieH** [comment]
@eborrell Maybe we should change the 3-state stationary P matrix to be a bit more complicated, because now P=P_back (or was that on purpose)?

**Comment by eborrell** [comment]
@LuzieH definetely! I have changed P for a random stochastic matrix and the dimension of the state space can be given as a parameter (see tests/conftest.py). 
$ pytest (has S=100 as default), or
$ pytest --dim-state-space 1000 (has S=1000)

**Comment by eborrell** [comment]
@LuzieH I have made a wiki page for the test docu and some commands. Have a look! :)
https://github.com/LuzieH/pytpt/wiki/Tests

**Comment by LuzieH** [comment]
@eborrell The Wiki looks great! Good idea to do that :) 

And I realized one more thing regarding random P matrices: I just had a failed test_reac_density(self, small_network) since the normalized reactive density had nan values. When I ran it again it was successful. Maybe random matrices are not such a good thing, because one can't find out where the exact error comes from, it's not reproducible and depends on the random seed. My guess for why the test failed is that the random matrix wasn't irreducible (which I am not sure how to enforce?). But on a second thought, producing irreducible matrices is very likely since the sampled transition matrix with high probability has non-zero values in each entry. So then I don't know about the error?

What do you think? Do you have an explanation?

**Comment by LuzieH** [comment]
@eborrell when writing the tests for the finite time case, I defined the transition matrix function using functools.partial, but the class finite threw an error at this due to :  `assert isfunction(P) == True` , I commented it out in the finite class, but have to find a solution for that. maybe isfunction is not general enough?

**Comment by eborrell** [comment]
@LuzieH Regarding the failed test, I agree that we should also test the methods against a not random matrix. 
For the tests with random matrices we could write a validator which tells us if a matrix is irreducible or not and then test that in the beginning and imply that if this fails the test should not continue (I think that this happens anyway.)
For the test with a given matrix I would impose that this matrix is irreducible.

**Comment by eborrell** [comment]
Hey @LuzieH. Here the brief review :)
- I made a validator for irreducible matrices. 
- I found how to load data in the tests (You need to install the package pytest-datadir). This allows us to actually test the small_network example and the triple well (therefore I deleted the pipelines test). I adapt the test so that if the flag --small-network is given we test against the small network example (same can be done with the triple well). Some refractoring has been done as well
- Regarding the time spend in each method, now we can see how much time each test needs by adding the flag --durations=0, which already gives us an idea if a method is fast or slow.
- I did not have time for continuing with the vectorization.

**Comment by LuzieH** [comment]
@eborrell I also get another bug/warning (but I am not sure why it appears): `  <string>:6: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.` 
it shows up for all finite-time tests: ie..e test_transition_matri, test_density, test_committors etc.

**Comment by eborrell** [comment]
@LuzieH about the default setting of --small-network: To have default False one has to have the action 'store_true'. I changed it again. Can you test that works fine for you?

**Comment by LuzieH** [comment]
> 
> 
> @LuzieH about the default setting of --small-network: To have default False one has to have the action 'store_true'. I changed it again. Can you test that works fine for you?

It works!

**Comment by LuzieH** [comment]
@eborrell my update of today: 
- I added the validation.py file to src/pytpt (if you dont like it, I can undo it) - in that way we can now check that the inputted transition matrix in the stationary case is irreducible and row-stochastic. 
- also have a look at my comment on your commit "vectorization of backward_transitions for the stationary case"

**Comment by eborrell** [comment]
Hey @LuzieH, this is a brief review of whats new:
- the attributes are changed from protected to public. To do so I need to rename the attribute reac_norm_factor.
- the broadcasting tests are done for the periodic case. 
- short flags by setting the test parameters (-S, -M and -N) are added.
- I added the methods backward_transitions, forward committor and backward committor for the finite case although I would keep using the method committors because we just need one loop. With the same idea I open a small issue https://github.com/LuzieH/pytpt/issues/42 where we can discuss how to optimize the computation of the statistics for the finite case. My idea is to just use to 2 loops over n; 1 for the committors and 1 for the reac density and the reac_current.
